package:
  name: owslib
  version: 0.10.3

source:
  fn: OWSLib-0.10.3.tar.gz
  url: https://pypi.python.org/packages/source/O/OWSLib/OWSLib-0.10.3.tar.gz
  md5: 07ebf7dbaebf4d935c7636bb96732103

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-dateutil
    - pytz
    - requests
    - lxml
    - pyproj

test:
  imports:
    - owslib.coverage
    - owslib.waterml
    - owslib.swe.observation
    - owslib.swe.sensor
    - owslib
    - owslib.feature
    - owslib.swe

about:
  home: https://geopython.github.io/OWSLib
  license: BSD License
  summary: 'OGC Web Service utility library'
