package:
    name: h5netcdf
    version: "0.2.2"

source:
    fn: h5netcdf-0.2.2.tar.gz
    url: https://pypi.python.org/packages/source/h/h5netcdf/h5netcdf-0.2.2.tar.gz
    md5: 5de72a6b8e4cc071ca2154fadf3681e3

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - h5py
    run:
        - python
        - h5py

test:
    imports:
        - h5netcdf

about:
    home: https://github.com/shoyer/h5netcdf
    license: BSD License
    summary: 'netCDF4 via h5py'
