{% set version = "1.0.2" %}

package:
  name: freexl
  version: {{ version }}

source:
  fn: freexl-{{ version }}.tar.gz
  url: http://www.gaia-gis.it/gaia-sins/freexl-{{ version }}.tar.gz
  md5: 9954640e5fed76a5d9deb9b02b0169a0
  patches:  # [win]
    - makefile.vc.patch  # [win]
    - nmake.opt.patch  # [win]
    - freexl.c.patch  # [win]

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - libiconv  # [win]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - libiconv  # [win]

test:
  commands:
    - test -f $PREFIX/lib/libfreexl.a  # [not win]
    - conda inspect linkages -p $PREFIX freexl  # [not win]
    - conda inspect objects -p $PREFIX freexl  # [osx]

about:
  home: https://www.gaia-gis.it/fossil/freexl/index
  license: LGPL-2.1
  summary: 'Extract valid data from within an Excel.'

extra:
  recipe-maintainers:
    - ocefpaf
