{% set version = "0.5.0" %}

package:
    name: utilities
    version: {{ version }}

source:
    fn: utilities-v{{ version }}.tar.gz
    url: https://github.com/pyoceans/utilities/archive/v{{ version }}.tar.gz
    sha256: f90a8af2d1518bb8c0aa3e7c88bfde18b6af3e1ef65e024acc37bdb16f6ce041

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - iris
        - lxml
        - tardis
        - oceans
        - pandas
        - folium
        - owslib
        - pyugrid
        - requests
        - scikit-learn
        - beautifulsoup4
        - ipython-notebook

test:
    imports:
        - utilities

about:
    home: https://github.com/pyoceans/utilities.git
    license: MIT
    summary: IOOS/SECOORA utilities.py module

extra:
  recipe-maintainers:
    - ocefpaf
