package:
    name: oil_library
    version: 0.1

source:
    git_url: https://github.com/NOAA-ORR-ERD/PyGnome.git
    git_tag: master

build:
    number: 0
    skip: True  # [py3k]

requirements:
    build:
        - python
        - setuptools
        - sqlalchemy
        - unit_conversion
        - zope.sqlalchemy
        - numpy
        - repoze.lru
        - awesome-slugify
    run:
        - python
        - sqlalchemy
        - unit_conversion
        - zope.sqlalchemy
        - numpy
        - repoze.lru
        - awesome-slugify
        - transaction

test:
    imports:
        - oil_library
    requires:
        - pytest

about:
    home: https://github.com/NOAA-ORR-ERD/PyGnome
    license: Public Domain
    summary: 'Oil library'
