package:
    name: django-extensions
    version: "1.6.1"

source:
    fn: django-extensions-1.6.1.tar.gz
    url: https://pypi.python.org/packages/source/d/django-extensions/django-extensions-1.6.1.tar.gz
    md5: bcd7662eb69a5cf726b927e61ee8013e

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - six >=1.2
        - django >=1.7

test:
    imports:
        - django_extensions

about:
    home: http://github.com/django-extensions/django-extensions
    license: MIT License
    summary: 'Extensions for Django'
