package:
  name: esmf
  version: 7.0.0

build:
  number: 0
  skip: True # [win]

source:
  git_url: git://git.code.sf.net/p/esmf/esmf
  git_tag: ESMF_7_0_0

requirements:
  build:
    - netcdf-fortran
    - mpich2 # [linux]
  run:
    - netcdf-fortran
    - mpich2 # [linux]

about:
  home: http://www.earthsystemmodeling.org/
  license: The University of Illinois/NCSA Open Source License (NCSA)
  summary: The Earth System Modeling Framework (ESMF) is software for building and coupling weather, climate, and related models.
