package:
    name: pykdtree
    version: 1.1.1

source:
    fn: pykdtree-1.1.1.tar.gz
    url: https://pypi.python.org/packages/source/p/pykdtree/pykdtree-1.1.1.tar.gz
    md5: 936b0844b3d06d8f2f2a1ca40f587cfb
    patches:
        - win_comp.patch  # [win]

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - python
        - setuptools
        - numpy x.x
    run:
        - python
        - numpy x.x

test:
    imports:
        - pykdtree

about:
    home: https://pypi.python.org/pypi/pykdtree
    license: GNU General Public License v3 (GPLv3)
    summary: Fast kd-tree implementation with OpenMP-enabled queries

extra:
    recipe-maintainers:
        - ocefpaf
