package:
    name: ioos_qartod
    version: "0.0.2"

source:
    fn: ioos_qartod-0.0.2.tar.gz
    url: https://pypi.python.org/packages/source/i/ioos_qartod/ioos_qartod-0.0.2.tar.gz
    md5: d83d2ba1adcf36eae80bf86a536ce112

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pandas
        - quantities
        - pyproj

test:
    imports:
        - ioos_qartod

about:
    home: https://pypi.python.org/pypi/ioos_qartod
    license: Apache 2.0
    summary: 'Collection of utilities, scripts and tests to assist in automated quality assurance.'
