package:
    name: geolinks
    version: "0.2.0"

source:
    fn: geolinks-0.2.0.tar.gz
    url: https://pypi.python.org/packages/source/g/geolinks/geolinks-0.2.0.tar.gz
    md5: d3deb3ae7afd2670b8deb9bf00c7a13c

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - geolinks

about:
    home: https://github.com/geopython/geolinks
    license: MIT
    summary: 'Utilities to deal with geospatial links'
