package:
    name: basemap-data-hires
    version: 1.0.8.dev0

source:
  git_url: https://github.com/matplotlib/basemap.git
  git_tag: 116aefb

build:
    number: 0

requirements:
    build:
        - basemap >1.0.7
    run:
        - basemap >1.0.7

test:
    imports:
        - mpl_toolkits.basemap

about:
    home: http://matplotlib.org/basemap
    license: GPLv2.0
    summary: Plot on map projections (with coastlines and political boundaries) using matplotlib

extra:
    recipe-maintainers:
        - ocefpaf
