package:
    name: pywavelets
    version: "0.4.0"

source:
    fn: PyWavelets-0.4.0.tar.gz
    url: https://pypi.python.org/packages/source/P/PyWavelets/PyWavelets-0.4.0.tar.gz
    md5: 5b41cd6bf4bd7645aee8eaae72816853

requirements:
    build:
        - python
        - cython
        - numpy x.x
    run:
        - python
        - numpy x.x

test:
    requires:
        - nose

about:
    home: https://github.com/PyWavelets/pywt
    license: MIT
    summary: 'Discrete Wavelet Transforms in Python.'
