package:
  name: esmpy
  version: 7.0.0

build:
  number: 0
  skip: True # [win]
  skip: True # [py3k]

source:
  git_url: git://git.code.sf.net/p/esmf/esmf
  git_tag: ESMF_7_0_0

requirements:
  build:
    - python >=2.7,<3
    - numpy
    - esmf
  run:
    - python
    - numpy
    - esmf
    - mpi4py # [linux]

# TODO (bekozi): Use run_test.sh with ESMPy 7 release.
test:
  imports:
    - ESMF

about:
  home: https://www.earthsystemcog.org/projects/esmpy/
  license: The University of Illinois/NCSA Open Source License (NCSA)
  summary: ESMPy is a Python interface to the Earth System Modeling Framework (ESMF) regridding utility.
