package:
    name: paegan-transport
    version: "1.0.5"

source:
    fn: paegan-transport-1.0.5.tar.gz
    url: https://pypi.python.org/packages/source/p/paegan-transport/paegan-transport-1.0.5.tar.gz
    md5: 63ab6779286e2cf42f127f7ccadac32f

build:
    number: 0
    skip: True  # [py35 and win]

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - paegan
        - fiona
        - requests
        - redis-py  # [not win]
        - geojson
        - pytables

test:
    imports:
        - paegan.transport
        - paegan.transport.bathymetry
        - paegan.transport.controllers # [not win]
        - paegan.transport.export
        - paegan.transport.forcers
        - paegan.transport.models
        - paegan.transport.models.behaviors
        - paegan.transport.parallel_manager
        - paegan.transport.particles
        - paegan.transport.shoreline

about:
    home: https://github.com/axiom-data-science/paegan-transport
    license: GNU General Public License v3 (GPLv3)
    summary: 'Paegan-Transport - The parallellized Langragian transport model for NetCDF/OPeNDAP data, written on top of Paegan'
