{% set version = "3.0" %}

package:
  name: libmo_unpack
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/SciTools/libmo_unpack/archive/v{{ version }}.tar.gz
  sha256: dc64f38ce588c8780d53e91c399cf836588e2afd7d1b7191dc286bf5eca9c75f

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - check
    - automake
    - libtool
    - pkg-config

test:
  commands:
    - conda inspect linkages -p $PREFIX libmo_unpack  # [not win]
    - conda inspect objects -p $PREFIX libmo_unpack  # [osx]

about:
  home: https://github.com/SciTools/libmo_unpack
  license: BSD 3-Clause
  summary: 'Met Office PP/FieldsFile compression schemes.'

extra:
  recipe-maintainers:
    - ocefpaf
