package:
    name: yaml2ncml
    version: "0.3.0"

source:
    git_url: https://github.com/usgs-cmg/yaml2ncml.git
    git_tag: 0.3.0

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pyyaml
        - docopt
        - netcdf4

test:
    imports:
        - yaml2ncml

about:
    home: https://github.com/rsignell-usgs/yaml2ncml
    license: MIT License
    summary: 'NcML aggregation from YAML specification'
