package:
    name: pygeoif
    version: 0.6

source:
    fn: pygeoif-0.6.tar.gz
    url: https://pypi.python.org/packages/source/p/pygeoif/pygeoif-0.6.tar.gz
    md5: e5d423724f9894aa2b2a1a8eb2314051

build:
    number: 0
    preserve_egg_dir: True
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - pygeoif
    requires:
        - pytest

about:
    home: https://github.com/cleder/pygeoif/
    license: GNU Library or Lesser General Public License (LGPL)
    summary: A basic implementation of the __geo_interface__

extra:
    recipe-maintainers:
        - ocefpaf
        - benjwadams
        - daf
