package:
    name: siphon
    version: "0.3.2"

source:
    fn: siphon-0.3.2.tar.gz
    url: https://pypi.python.org/packages/source/s/siphon/siphon-0.3.2.tar.gz
    md5: dd08ff89b1176939d59acae0d544dd81

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - protobuf >=3.0.0a3
        - requests
        - netcdf4

test:
    imports:
        - siphon
        - siphon.cdmr
        - siphon.catalog
        - siphon.ncss
        - siphon.radarserver

about:
    home: https://github.com/Unidata/siphon
    license: MIT License
    summary: 'A collection of Python utilities for interacting with the Unidata technology stack.'
