{% set version = "1.5.15" %}

package:
    name: shapely
    version: {{ version }}

source:
    fn: Shapely-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/S/Shapely/Shapely-{{ version }}.tar.gz
    md5: c2e06fb89cdbd959b89ae69794ede3c0
    patches:
        - geos_c.patch

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - geos >=3.4
        - cython
        - numpy x.x
        - msinttypes  # [win]
    run:
        - python
        - geos >=3.4
        - numpy x.x

test:
    imports:
        - shapely
        - shapely.speedups._speedups
        - shapely.vectorized._vectorized

about:
    home: https://github.com/Toblerity/Shapely
    license: BSD
    summary: Python package for manipulation and analysis of geometric objects in the Cartesian plane

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
