package:
    name: hdfeos2
    version: "2.19.1"

source:
    fn: HDF-EOS2.19v1.00.tar.Z
    url: ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/HDF-EOS2.19v1.00.tar.Z
    md5: b8648484fc78a2db7073dd603f3fb251

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - hdf4
        - zlib
        - jpeg
        - gcc
    run:
        - hdf4
        - zlib
        - jpeg

test:
    commands:
        - conda inspect linkages hdfeos2 --name _test

about:
    home: http://hdfeos.org/index.php
    license: BSD
    summary: 'Hierarchical Data Format - Earth Observing System: self-describing file format for transfer of various types of data between different machines based upon HDF.'
