package:
    name: simplekml
    version: "1.2.8"

source:
    fn: simplekml-1.2.8.zip
    url: https://pypi.python.org/packages/source/s/simplekml/simplekml-1.2.8.zip
    md5: 16ac3ad2639c7e50ec769baf33a0278e

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - simplekml

about:
    home: http://code.google.com/p/simplekml/
    license: GNU General Public License (GPL)
    summary: 'A Simple KML creator'
