package:
    name: cdo
    version: 1.7.0

source:
    fn: cdo-1.7.0.tar.gz
    url: https://code.zmaw.de/attachments/download/11392/cdo-1.7.0.tar.gz
    md5: cca30c3c79335ad734e1838806f7bfc2

build:
    number: 2
    skip: True  # [win]

requirements:
    build:
        - jasper
        - libnetcdf
        - netcdf-fortran
        - proj.4
        - gcc
        - libuuid
    run:
        - jasper
        - libnetcdf
        - netcdf-fortran
        - proj.4
        - libgcc
        - libuuid

test:
    commands:
        - cdo -h
        - conda inspect linkages cdo --name _test

about:
    home: https://code.zmaw.de/projects/cdo
    license: GNU General Public License v2
    summary: CLI tools to manipulate and analyse Climate and NWP model Data

extra:
    recipe-maintainers:
        - ocefpaf
