package:
    name: regex
    version: 2016.03.02

source:
    fn: regex-2016.03.02.tar.gz
    url: https://pypi.python.org/packages/source/r/regex/regex-2016.03.02.tar.gz
    md5: 7e6056389b39af87cf4e60d8ac88402a

build:
    script: python setup.py install
    number: 0

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - regex

about:
    home: https://code.google.com/p/mrab-regex-hg/
    license: Python Software Foundation License
    summary: Alternative regular expression module, to replace re.

extra:
    recipe-maintainers:
        - ocefpaf
