package:
    name: pyresample
    version: 1.1.6

source:
    fn: pyresample-1.1.6.tar.gz
    url: https://pypi.python.org/packages/source/p/pyresample/pyresample-1.1.6.tar.gz
    md5: 1f1b0cbf8a104b082ee742418d0bb07a

build:
    script: python setup.py install --single-version-externally-managed --record record.txt
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - scipy
        - pyproj
        - numpy
        - configobj
        - pykdtree  # [not win]
        - numexpr

test:
    imports:
        - pyresample

about:
  home: https://github.com/mraspaud/pyresample/
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'Resampling of remote sensing data in Python'
