package:
    name: basemap
    version: 1.0.8.dev

source:
  git_url: https://github.com/matplotlib/basemap.git
  git_tag: master

build:
    number: 0

requirements:
    build:
        - python
        - numpy x.x
        - geos >=3.4.2
    run:
        - python
        - numpy x.x
        - geos >=3.4.2
        - matplotlib
        - pyproj

test:
    imports:
        - mpl_toolkits.basemap
about:
    home: http://matplotlib.org/basemap
    license: GNU GPL
    summary: Plot on map projections (with coastlines and political boundaries) using matplotlib

extra:
    recipe-maintainers:
        - ocefpaf
