package:
    name: netcdf-fortran
    version: 4.4.2

build:
    number: 0

source:
    git_url: https://github.com/Unidata/netcdf-fortran
    git_tag: v4.4.2

requirements:
    build:
        - libnetcdf
    run:
        - libnetcdf

about:
    home: https://github.com/Unidata/netcdf-fortran
    license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
    summary: "Unidata NetCDF Fortran Library"
