package:
    name: octant
    version: "0.8.dev"

source:
    git_url: https://github.com/hetland/octant.git
    git_tag: master
    patches:
        - setuptools.patch

build:
    number: 3
    skip: True  # [win]

requirements:
    build:
        - python >=2.7,<3
        - numpy x.x
        - setuptools
        - matplotlib
        - mingwpy  # [win]
    run:
        - python
        - numpy x.x
        - netcdf4
        - matplotlib
        - basemap

test:
    imports:
        - octant

about:
    home: https://github.com/hetland/octant
    license:  MIT
    summary: 'Ocean C-grid model setup and analysis tools, for the numerical mariner.'
