package:
    name: palettable
    version: "2.1.1"

source:
    fn: palettable-2.1.1.tar.gz
    url: https://pypi.python.org/packages/source/p/palettable/palettable-2.1.1.tar.gz
    md5: 60adcbda83e1eaa331c5fdc5dfbcc4ff

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - palettable
        - palettable.colorbrewer
        - palettable.tableau
        - palettable.wesanderson

about:
    home: https://jiffyclub.github.io/palettable/
    license: MIT License
    summary: 'Color palettes for Python'
