{% set version = "2.2.20" %}

package:
  name: udunits2
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/Unidata/UDUNITS-2/archive/v{{ version }}.tar.gz
  sha1: a0d30024af16749a4a5ca60133b32735ae52f9e2

build:
  number: 0
  detect_binary_files_with_prefix: True
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python  # [win]
    # Use AppVeyor's cmake.
    #- cmake  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - automake  # [not win]
    - libtool  # [not win]
    - texinfo  # [not win]
    - expat
  run:
    - expat
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

test:
  commands:
    - udunits2 -h
    - udunits2 -H meter -W miles
    - conda inspect linkages -p $PREFIX udunits2  # [not win]
    - conda inspect objects -p $PREFIX udunits2  # [osx]

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  license: https://github.com/Unidata/UDUNITS-2/blob/master/COPYRIGHT
  summary: 'The UDUNITS package supports units of physical quantities.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
