{% set version = "4.4.1" %}

package:
  name: libnetcdf
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/Unidata/netcdf-c/archive/v{{ version }}.tar.gz
  sha256: 17599385fd76ccdced368f448f654de2ed000fece44dece9fb5d598798b4c9d6
  patches:  # [win]
    - dfile.c.patch  # [win]
    - dim.c.patch  # [win]

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python  # [win]
    # Use AppVeyor's cmake.
    - cmake  # [not win]
    - pkg-config  # [not win]
    - msinttypes  # [win]
    - curl
    - zlib 1.2.*
    - hdf4
    - hdf5 1.8.17|1.8.17.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
  run:
    - curl
    - zlib 1.2.*
    - hdf4
    - hdf5 1.8.17|1.8.17.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

test:
  commands:
    - nc-config --all  # [unix]
    - test -f ${PREFIX}/lib/libnetcdf.a  # [unix]
    - test -f ${PREFIX}/lib/libnetcdf.so  # [linux]
    - test -f ${PREFIX}/lib/libnetcdf.dylib  # [osx]
    - conda inspect linkages -p $PREFIX libnetcdf  # [linux]
    - conda inspect objects -p $PREFIX libnetcdf  # [osx]

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  summary: 'Libraries and data formats that support array-oriented scientific data.'

extra:
  recipe-maintainers:
    - ocefpaf
