package:
    name: pastescript
    version: "2.0.2"

source:
    fn: PasteScript-2.0.2.tar.gz
    url: https://pypi.python.org/packages/source/P/PasteScript/PasteScript-2.0.2.tar.gz
    md5: ccb3045445097192ca71a13b746c77b2

build:
    number: 0

requirements:
    build:
        - python >=2.7,<3
        - setuptools
        - paste >=1.3
        - pastedeploy
        - six
    run:
        - python
        - paste >=1.3
        - pastedeploy
        - six

test:
    imports:
        - paste
        - paste.script
        - paste.script.util
    requires:
        - nose >=0.11

about:
    home: http://pythonpaste.org/script/
    license: MIT License
    summary: 'A pluggable command-line frontend, including commands to setup package file layouts'
