package:
    name: libuuid
    version: 1.0.3

source:
    url: ftp://ftp.nersc.no/pub/Aleks/libuuid-1.0.3.tar.gz
    fn: libuuid-1.0.3.tar.gz

build:
    number: 0
    skip: True  # [win]


requirements:
    build:
        - gcc
    run:
        - libgcc

about:
    home: http://sourceforge.net/projects/libuuid/
    license: BSD
    summary: Portable uuid C library

extra:
    recipe-maintainers:
        - ocefpaf
