{% set version = "2.5.39" %}

package:
  name: flex
  version: {{ version }}

source:
  fn: flex-{{ version }}.tar.gz
  url: http://sourceforge.net/projects/flex/files/flex-{{ version }}.tar.gz
  md5: e133e9ead8ec0a58d81166b461244fde
  patches:
    # https://sourceforge.net/p/flex/bugs/182/
    - Makefile.am.patch
    # https://sourceforge.net/p/flex/bugs/169/
    - 0001-bison-test-fixes-Do-not-use-obsolete-bison-construct.patch

build:
  skip: True  # [win]
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - m4

test:
  commands:
    - flex --help
    - test -f ${PREFIX}/include/FlexLexer.h
    - test -f ${PREFIX}/lib/libfl.a
    - test -f ${PREFIX}/lib/libfl_pic.a
    - test -f ${PREFIX}/lib/libfl.dylib  # [osx]
    - test -f ${PREFIX}/lib/libfl_pic.dylib  # [osx]
    - test -f ${PREFIX}/lib/libfl.so  # [linux]
    - test -f ${PREFIX}/lib/libfl_pic.so  # [linux]
    - conda inspect linkages -p $PREFIX flex  # [not win]
    - conda inspect objects -p $PREFIX flex  # [osx]

about:
  home: http://flex.sourceforge.net/
  license: BSD 2-Clause
  summary: 'The Fast Lexical Analyzer.'

extra:
  recipe-maintainers:
    - ocefpaf
