package:
    name: genshi
    version: "0.7"

source:
    fn: Genshi-0.7.tar.gz
    url: https://pypi.python.org/packages/source/G/Genshi/Genshi-0.7.tar.gz
    md5: 54e64dd69da3ec961f86e686e0848a82

build:
    number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
    imports:
        - genshi
        - genshi.filters
        - genshi.filters.tests
        - genshi.template
        - genshi.template.tests
        - genshi.template.tests.templates
        - genshi.tests

about:
    home: http://genshi.edgewall.org/
    license: BSD License
    summary: 'A toolkit for generation of output for the web'
