package:
    name: hdfeos5
    version: "5.1.15"

source:
    fn: HDF-EOS5.1.15.tar.Z
    url: ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos5/latest_release/HDF-EOS5.1.15.tar.Z
    md5: 5d607a13dd42e559bfc90e278a8ec919
    patches:
        # http://hdfeos.org/forums/showthread.php?t=673
        - EHapi.c.patch

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - hdf5
        - zlib
        - gcc
    run:
        - hdf5
        - zlib

test:
    commands:
        - conda inspect linkages hdfeos5 --name _test

about:
    home: http://hdfeos.org/index.php
    license: BSD
    summary: 'Hierarchical Data Format - Earth Observing System: self-describing file format for transfer of various types of data between different machines based upon HDF.'
