{% set version = "0.34.0" %}

package:
    name: rasterio
    version: {{ version }}

source:
    fn: rasterio-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/r/rasterio/rasterio-{{ version }}.tar.gz
    md5: 203c1336e94900b3b98f31cb3f011c18

build:
    number: 1
    entry_points:
        - rio = rasterio.rio.main:main_group

requirements:
    build:
        - python
        - numpy x.x
        - cython
        - gdal 1.11.4
        - setuptools
    run:
        - python
        - affine
        - cligj
        - enum34  # [py27]
        - numpy x.x
        - snuggs
        - gdal 1.11.4
        - click-plugins

test:
    imports:
        - rasterio
    commands:
        - rio --help

about:
    home: https://github.com/mapbox/rasterio
    license: BSD 3-Clause
    summary: Rasterio reads and writes geospatial raster datasets

extra:
    recipe-maintainers:
        - ocefpaf
        - ceholden
