package:
    name: pygc
    version: "0.2"

source:
    fn: pygc-0.2.tar.gz
    url: https://pypi.python.org/packages/source/p/pygc/pygc-0.2.tar.gz
    md5: 76d35e92a60086ef76d37178ae92fda1

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - numpy
    run:
        - python
        - numpy

test:
    imports:
        - pygc

about:
    home: https://github.com/kwilcox/pygc
    license: GNU General Public License v3 (GPLv3)
    summary: "Great Circle calculations in Python using Vincenty's formulae"
