package:
    name: thredds_crawler
    version: "1.2.0"

source:
    fn: thredds_crawler-1.2.0.tar.gz
    url: https://pypi.python.org/packages/source/t/thredds_crawler/thredds_crawler-1.2.0.tar.gz
    md5: 36e610681ed4023d26d24d3a55c03a6b

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - requests
        - lxml
    run:
        - python
        - requests
        - lxml
        - netcdf4
        - pytz

test:
    imports:
        - tests
        - thredds_crawler

about:
    home: https://github.com/asascience-open/thredds_crawler
    license:  GNU General Public License v3 (GPLv3)
    summary: 'A Python library for crawling THREDDS servers'
