package:
    name: gpxpy
    version: 1.1.1

source:
    fn: gpxpy-1.1.1.tar.gz
    url: https://pypi.python.org/packages/source/g/gpxpy/gpxpy-1.1.1.tar.gz
    md5: 55b62ccd2acc7cc441efb82230b10b48

build:
    number: 0
    script: python setup.py install

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - gpxpy

about:
    home: http://www.trackprofiler.com/gpxpy/index.html
    license: Apache License, Version 2.0
    summary: GPX file parser and GPS track manipulation library

extra:
    recipe-maintainers:
        - ocefpaf
