package:
    name: pykml
    version: "0.1.0"

source:
    fn: pykml-0.1.0.tar.gz
    url: https://pypi.python.org/packages/source/p/pykml/pykml-0.1.0.tar.gz
    md5: 1acdfbc098be0222c50f55f46ace62e1

build:
    preserve_egg_dir: True
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - lxml >=2.2.6

test:
    imports:
        - pykml
    requires:
        - nose

about:
    home: http://pypi.python.org/pypi/pykml
    license: BSD License
    summary: 'Python KML library'
