package:
    name: numdifftools
    version: "0.9.14"

source:
    fn: numdifftools-0.9.14.zip
    url: https://pypi.python.org/packages/source/N/Numdifftools/numdifftools-0.9.14.zip
    md5: 04add9a62433466923764d9ef501eeb5

build:
    skip: True  # [py35]
    number: 0

requirements:
    build:
        - python
        - setuptools
        - setuptools_scm
        - pyscaffold >=2.4rc1,<2.5a0
        - six
    run:
        - python
        - numpy
        - scipy
        - algopy
        - six

test:
    imports:
        - numdifftools
        - numdifftools.tests
    requires:
        - pytest
        - pytest-cov  # [not py3k]

about:
    home: https://github.com/pbrod/numdifftools/
    license: BSD
    summary: "Solves automatic numerical differentiation problems in one or more variables."
