package:
    name: oceans
    version: "0.2.5"

source:
    fn: oceans-0.2.5.tar.gz
    url: https://pypi.python.org/packages/source/o/oceans/oceans-0.2.5.tar.gz
    md5: f8a7f628fcfffeafe5465eabc2e33400

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - pandas
        - gsw
        - seawater
        - shapely
        - netcdf4
        - ctd
        - iris  # [not py3k]

test:
    imports:
        - oceans

about:
    home: http://pypi.python.org/pypi/oceans/
    license: MIT License
    summary: 'Misc functions for oceanographic data analysis'
