package:
    name: django-autoslug
    version: "1.9.3"

source:
    fn: django-autoslug-1.9.3.tar.gz
    url: https://pypi.python.org/packages/source/d/django-autoslug/django-autoslug-1.9.3.tar.gz
    md5: d91e4f04869a282398ca6efc623f2b34

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - django

#test:
    #imports:
        #- autoslug

about:
    home: http://bitbucket.org/neithere/django-autoslug/
    license: GNU Library or Lesser General Public License (LGPL)
    summary: 'An automated slug field for Django.'
