package:
    name: python-ternary
    version: "1.0"

source:
    fn: python-ternary-1.0.tar.gz
    url: https://pypi.python.org/packages/source/p/python-ternary/python-ternary-1.0.tar.gz
    md5: b4afa32a9cb8b8c7156ba9f9f9b481f8

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python
        - matplotlib >=1.4

test:
    imports:
        - ternary
about:
    home: https://github.com/marcharper/python-ternary
    license: MIT License
    summary: 'Make ternary plots in matplotlib'
