{% set version = "2.0.1" %}
{% set commit = "348704bab6e34b1da297e01350ff93465a45d306" %}

package:
    name: mocsy
    version: {{ version }}

source:
    fn: mocsy-{{ commit }}.tar.gz
    url: https://github.com/ocefpaf/mocsy/archive/{{ commit }}.tar.gz
    sha256: f78e03bacd5c325f0230a4780ac334f052852c1f52bc71bad5a4f6c586c1e22b

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - mingwpy  # [win]
        - numpy x.x
        - gcc  # [not win]
    run:
        - python
        - numpy x.x
        - libgcc  # [not win]

test:
    imports:
        - mocsy

about:
    home: https://github.com/jamesorr/mocsy.git
    license: MIT
    summary: Routines to model ocean carbonate system thermodynamics

extra:
    recipe-maintainers:
        - ocefpaf
