package:
    name: httpretty
    version: "0.8.14"

source:
    fn: httpretty-0.8.14.tar.gz
    url: https://pypi.python.org/packages/source/h/httpretty/httpretty-0.8.14.tar.gz
    md5: 2a6bbf270fafc77647b0479d95d0544c

build:
    number: 0
    skip: True  # [py3k]

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - httpretty

about:
    home: http://github.com/gabrielfalcao/httpretty
    license: MIT License
    summary: 'HTTP client mock for Python'
