package:
    name: mplleaflet
    version: "0.0.5"

source:
    fn: mplleaflet-0.0.5.tar.gz
    url: https://pypi.python.org/packages/source/m/mplleaflet/mplleaflet-0.0.5.tar.gz
    md5: cf8ec819862e4486f477fb71101477f1

build:
    number: 0


requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - jinja2
        - mplexporter

test:
    imports:
        - mplleaflet

about:
    home: https://github.com/jwass/mplleaflet
    license: BSD 3-clause
    summary: 'Convert Matplotlib plots into Leaflet web maps'
