{% set version = "3.0.4" %}

package:
  name: bison
  version: {{ version }}

source:
  fn: bison-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/bison/bison-{{ version }}.tar.gz
  md5: a586e11cd4aff49c3ff6d3b6a4c9ccf8

build:
  skip: True  # [win]
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m4
    - flex

test:
  commands:
    - yacc --help   # [not win]
    - bison --help  # [not win]
    - conda inspect linkages -p $PREFIX bison  # [not win]
    - conda inspect objects -p $PREFIX bison  # [osx]

about:
  home: https://www.gnu.org/software/bison/
  license: GPL-3.0
  summary: 'General purpose parser generator converting annotated context-free grammar to a deterministic LR/GLR parser.'

extra:
  recipe-maintainers:
    - ocefpaf
