package:
    name: scp
    version: "0.10.2"

source:
    fn: scp-0.10.2.tar.gz
    url: https://pypi.python.org/packages/source/s/scp/scp-0.10.2.tar.gz
    md5: 4c581a7fc08b3597b542aab22c36dba3

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - paramiko
    run:
        - python
        - paramiko

test:
    imports:
        - scp

about:
    home: https://github.com/jbardin/scp.py.git
    license: LGPL
    summary: 'scp module for paramiko'
