package:
    name: pyshp
    version: "1.2.3"

source:
    fn: pyshp-1.2.3.tar.gz
    url: https://pypi.python.org/packages/source/p/pyshp/pyshp-1.2.3.tar.gz
    md5: f857099a57f93830e0c72a31e9c506a8

build:
    number: 0

requirements:
    build:
        - python
        - setuptools

    run:
        - python

about:
    home: https://pypi.python.org/pypi/pyshp
    license: MIT
    summary: Pure Python read/write support for ESRI Shapefile format.
