package:
    name: gridutils
    version: "v1.0"

source:
    git_url: https://github.com/sakov/gridutils-c.git
    git_tag: v1.0

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - nn
        - csa
    run:
        - nn
        - csa

about:
    home: https://github.com/sakov/gridutils-c.git
    license: Simplified BSD
    summary: "C library functions and command line utilities for working with curvilinear grids."
