package:
    name: wicken
    version: "0.2.0"

source:
    git_url: https://github.com/ioos/wicken.git
    git_tag: v0.2.0

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - lxml
        - petulant-bear

test:
    imports:
        - wicken

about:
    home: https://github.com/ioos/wicken
    license:  Apache 2.0
    summary: 'Maps metadata concepts to concrete specifications and file formats'
