package:
    name: qrcode
    version: "5.2.2"

source:
    fn: qrcode-5.2.2.tar.gz
    url: https://pypi.python.org/packages/source/q/qrcode/qrcode-5.2.2.tar.gz
    md5: 19b0c93e80087b31681080536f1bfbbd

build:
    number: 0
    entry_points:
        - qr = qrcode.console_scripts:main

requirements:
    build:
        - python
        - setuptools
        - six
    run:
        - python
        - six
        - colorama

test:
    imports:
        - qrcode
        - qrcode.image
        - qrcode.tests
    commands:
        - qr --help

about:
    home: https://github.com/lincolnloop/python-qrcode
    license: BSD License
    summary: 'QR Code image generator'
