package:
    name: nn
    version: "1.85.1"

source:
    git_url: https://github.com/sakov/nn-c.git
    git_tag: master

build:
    number: 0
    skip: True  # [win]

about:
    home: https://github.com/sakov/nn-c.git
    license: Simplified BSD License and triangle.[c,h] license, which is non-free for commercial use
    summary: "Natural Neighbours interpolation"
