package:
    name: ocgis
    version: 1.3.0

source:
    git_url: https://github.com/NCPP/ocgis.git
    git_tag: v1.3.0

build:
    number: 0
    skip: True # [py3k]

requirements:
    build:
        - python >=2.7,<3
        - fiona ==1.6.3
        - netcdf4
        - numpy
        - shapely
    run:
        - python
        - cf_units
        - fiona ==1.6.3
        - netcdf4
        - numpy
        - shapely
        - rtree

test:
  requires:
    - nose

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.
