package:
    name: jsanimation
    version: "0.1"

source:
    git_url: https://github.com/jakevdp/JSAnimation.git
    git_tag: master

build:
    number: 1

requirements:
    build:
        - python
    run:
        - python

about:
    home: http://github.com/jakevdp
    license: BSD
    summary: 'Javascript Animation exporter for matplotlib and IPython'
