{% set version = "1.10.0" %}

package:
  name: geopy
  version: {{ version }}

source:
  fn: geopy-{{ version }}.tar.gz
  url: https://github.com/geopy/geopy/archive/{{ version }}.tar.gz
  sha256: d1445731b20762b4e1d13e98d6370ff39a58fb29bd526afe1a44d510e91ee815

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - geopy
    - geopy.geocoders

about:
  home: https://github.com/geopy/geopy
  license: MIT
  summary: 'Python Geocoding Toolbox.'

extra:
  recipe-maintainers:
    - ocefpaf
