package:
    name: airsea
    version: "0.0.1.dev"

source:
    git_url: https://github.com/ocefpaf/python-airsea.git
    git_tag: master

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - numpy
    run:
        - python
        - numpy

test:
    imports:
        - airsea

about:
    home: http://github.com/ocefpaf/python-airsea
    license: MIT License
    summary: 'Airsea Library for Python'
