package:
    name: ghp-import
    version: "0.4.1"

source:
    fn: ghp-import-0.4.1.tar.gz
    url: https://pypi.python.org/packages/source/g/ghp-import/ghp-import-0.4.1.tar.gz
    md5: 99e018372990c03ab355aa62c34965c5

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

about:
    home: http://github.com/davisp/ghp-import
    license: Tumbolia Public License
    summary: 'Copy your docs directly to the gh-pages branch.'
