package:
    name: rasterio
    version: "0.31.0"

source:
    fn: rasterio-0.31.0.tar.gz
    url: https://pypi.python.org/packages/source/r/rasterio/rasterio-0.31.0.tar.gz
    md5: 511e1418127c6d30b91e279154a4b4a4

build:
    number: 0
    skip: True  # [win and py35]

    entry_points:
        - rio = rasterio.rio.main:cli

requirements:
    build:
        - python
        - numpy x.x
        - cython
        - gdal ==1.11.3
        - setuptools
    run:
        - python
        - affine
        - cligj
        - enum34  #  [py27]
        - numpy x.x
        - snuggs
        - gdal ==1.11.3
        - click-plugins

test:
    imports:
        - rasterio

about:
    home: https://github.com/mapbox/rasterio
    license: BSD
    summary: 'Rasterio reads and writes geospatial raster datasets'
