package:
    name: geopandas
    version: "0.1.1"

source:
    fn: geopandas-0.1.1.tar.gz
    url: https://pypi.python.org/packages/source/g/geopandas/geopandas-0.1.1.tar.gz
    md5: a01b5d3eb6bc097665a0ba297c39029f

build:
    skip: True  # [py35 and win]
    number: 2

requirements:
    build:
        - python
        - setuptools
        - cython
    run:
        - python
        - pandas
        - pyproj
        - shapely
        - fiona
        - gdal ==1.11.3  # We need to pin gdal until fiona works with gdal >2.
        - six
        - rtree
        - descartes
        - matplotlib
        - psycopg2  # [not win]
        - sqlalchemy
        - geopy ==1.10.0
        - pysal  # [not py3k]

test:
    imports:
        - geopandas
        - geopandas.io
    files:
        - test.cpg
        - test.dbf
        - test.shp
        - test.shx

about:
    home: http://geopandas.org
    license: BSD
    summary: 'Geographic pandas extensions'
