{% set version = "5.1.2" %}

package:
  name: giflib
  version: {{ version }}

source:
  fn: giflib-{{ version }}.tar.gz
  url: http://downloads.sourceforge.net/project/giflib/giflib-{{ version }}.tar.gz
  md5: 241a5825d00a36055fcc71874d97cf7b

build:
  number: 0
  skip: True  # [win]

test:
  commands:
    - gif2rgb -h
    - gifbuild -h
    - gifclrmp -h
    - gifecho -h
    - giffix -h
    - gifinto -h
    - giftext -h
    - conda inspect linkages -p $PREFIX giflib  # [not win]
    - conda inspect objects -p $PREFIX giflib  # [osx]

about:
  home: http://giflib.sourceforge.net
  license: MIT
  summary: 'Library for reading and writing GIF images.'

extra:
  recipe-maintainers:
    - ocefpaf
