package:
    name: cc-plugin-glider
    version: "1.0.1"

source:
    fn: cc-plugin-glider-1.0.1.tar.gz
    url: https://pypi.python.org/packages/source/c/cc-plugin-glider/cc-plugin-glider-1.0.1.tar.gz
    md5: 6ed920190fc861c5ed177d803557c383

build:
    number: 0
    preserve_egg_dir: True

requirements:
    build:
        - python >=2.7,<3
        - setuptools
    run:
        - python
        - compliance-checker >=1.0.0

test:
    imports:
        - cc_plugin_glider

about:
    home: https://github.com/ioos/compliance-checker
    license: Apache Software License
    summary: 'Compliance Checker Glider DAC plugin'
