package:
    name: py_gnome
    version: 0.1.1

source:
    git_url: https://github.com/NOAA-ORR-ERD/PyGnome.git
    git_tag: master

build:
    number: 0
    skip: True  # [py3k or linux]

requirements:
    build:
        - python
        - setuptools
        - cython
        - numpy x.x
        - colander
        - curl
        - geojson
        - gsw
        - libnetcdf
        - msinttypes  # [win]
        - netcdf4
        - oil_library
        - pillow
        - progressbar
        - psutil
        - pyzmq
        - scipy
        - six
        - sqlalchemy
    run:
        - python
        - numpy x.x
        - colander
        - curl
        - geojson
        - gsw
        - libnetcdf
        - netcdf4
        - oil_library
        - pillow
        - progressbar
        - psutil
        - pyzmq
        - scipy
        - six
        - sqlalchemy

test:
    imports:
        - gnome
    requires:
        - pytest
        - testfixtures

about:
    home: https://github.com/NOAA-ORR-ERD/PyGnome
    license: Public Domain
    summary: 'Python module for gnome oilspill modeling'
