package:
    name: snuggs
    version: "1.3.1"

source:
    fn: snuggs-1.3.1.tar.gz
    url: https://pypi.python.org/packages/source/s/snuggs/snuggs-1.3.1.tar.gz
    md5: f812255b9b89d178a96c39395dba263d


build:
    number: 1

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - click
        - numpy
        - pyparsing

test:
    requires:
        - pytest
    imports:
        - snuggs

about:
    home: https://github.com/mapbox/snuggs
    license: MIT
    summary: 'Snuggs are s-expressions for Numpy'
