package:
    name: keepalive
    version: "0.5"

source:
    fn: keepalive-0.5.tar.gz
    url: https://pypi.python.org/packages/source/k/keepalive/keepalive-0.5.tar.gz
    md5: 8cbc104142c094ee8052f4c560968e96

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - keepalive

about:
    home: https://github.com/wikier/keepalive
    license: Apache Software License
    summary: 'urllib keepalive support for python'
