package:
    name: windrose
    version: "1.6"

source:
    fn: windrose-1.6.tar.gz
    url: https://pypi.python.org/packages/source/w/windrose/windrose-1.6.tar.gz
    md5: 6394781fae13fc36bd9b8523475e9e4d
    patches:
        - setup-patch.patch

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - matplotlib
        - numpy

test:
    imports:
        - windrose

about:
    home: https://github.com/scls19fr/windrose
    license: CEA CNRS Inria Logiciel Libre License, version 2.1 (CeCILL-2.1)
    summary: 'Python Matplotlib, Numpy library to manage wind data, draw windrose (also known as a polar rose plot)'
