{% set version = "1.4.17" %}

package:
  name: m4
  version: {{ version }}

source:
  fn: m4-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/m4/m4-{{ version }}.tar.gz
  sha256: 3ce725133ee552b8b4baca7837fb772940b25e81b2a9dc92537aeaf733538c9e

build:
  number: 0
  skip: True  # [win]

test:
  commands:
    - m4 --help
    - m4 --version
    - conda inspect linkages -p $PREFIX m4  # [not win]
    - conda inspect objects -p $PREFIX m4  # [osx]

about:
  home: http://www.gnu.org/software/m4/
  license: GPL3
  summary: 'Implementation of the traditional Unix macro processor.'

extra:
  recipe-maintainers:
    - ocefpaf
