package:
    name: pymatbridge
    version: "0.5.2"

source:
    git_url: https://github.com/arokem/python-matlab-bridge.git
    git_tag: 0.5.2

build:
    number: 0

requirements:
    build:
        - python
        - pyzmq
        - numpy
    run:
        - python
        - pyzmq
        - numpy

test:
    imports:
        - pymatbridge

about:
    home: https://github.com/arokem/python-matlab-bridge
    license: BSD License
    summary: 'Python-MATLAB(R) Bridge and IPython'