package:
  name: cmake
  version: 3.5.0

source:
  url: https://cmake.org/files/v3.5/cmake-3.5.0.tar.gz  # [not win]
  fn: cmake-3.5.0.tar.gz # [not win]

  url: https://cmake.org/files/v3.5/cmake-3.5.0-win32-x86.zip  # [win]
  fn: cmake-3.5.0-win32-x86.zip # [win]

build:
  number: 3
  detect_binary_files_with_prefix: true

test:
  commands:
    - cmake --version

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  summary: CMake is an extensible, open-source system that manages the build process

extra:
  recipe-maintainers:
    - groutr
    - jakirkham
    - ocefpaf
    - msarahan
