package:
    name: geopy
    version: "1.11.0"

source:
    fn: geopy-1.11.0.tar.gz
    url: https://pypi.python.org/packages/source/g/geopy/geopy-1.11.0.tar.gz
    md5: b73445dc0069550bbd2b09162f7339b3

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - geopy
        - geopy.geocoders

about:
    home: https://github.com/geopy/geopy
    license: MIT License
    summary: 'Python Geocoding Toolbox'
