package:
    name: metakernel
    version: "0.12.3"

source:
    fn: metakernel-0.12.3.tar.gz
    url: https://pypi.python.org/packages/source/m/metakernel/metakernel-0.12.3.tar.gz
    md5: 1a9fcfe71c4e0abae00e14cfb951d257

build:
    script: python setup.py install --single-version-externally-managed --record record.txt
    number: 0

requirements:
    build:
        - python
        - setuptools
        - ipython >=3.0
    run:
        - python
        - ipython >=3.0

test:
    imports:
        - metakernel
        - metakernel.magics
        - metakernel.magics.tests
        - metakernel.tests
        - metakernel.utils

about:
    home: https://github.com/Calysto/metakernel
    license: BSD License
    summary: 'Metakernel for Jupyter'

extra:
    recipe-maintainers:
        - ocefpaf
