{% set version = "0.8.2" %}
{% set commit = "f5ee10617b84a681cb69e7a921aa1b1113d8debd" %}

package:
  name: rtree
  version: {{ version }}

source:
  fn: rtree-{{ version }}-{{ commit }}.tar.gz
  url: https://github.com/Toblerity/rtree/archive/{{ commit }}.tar.gz
  sha256: 97b1c7d9a17c1338468abc164a0283af69358b87e687700e0a60fc3f821ece0d
  patches:
    - find_libray.patch
    - setup-win.path  # [win]
    - find_libray-win32.patch  # [win32]

build:
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - libspatialindex
  run:
    - python
    - libspatialindex

test:
  imports:
    - rtree
  commands:
    - conda inspect linkages -p $PREFIX rtree  # [not win]
    - conda inspect objects -p $PREFIX rtree  # [osx]

about:
  home: http://toblerity.github.com/rtree/
  license: LGPL-2.1
  summary: 'R-Tree spatial index for Python GIS.'

extra:
  recipe-maintainers:
    - ocefpaf
