package:
    name: pygridgen
    version: "0.1.1"

source:
    git_url: https://github.com/phobson/pygridgen.git
    git_tag: 0.1.1

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - python
        - numpy
    run:
        - python
        - pandas
        - numpy
        - matplotlib
        - pyproj
        - csa
        - gridgen
        - gridutils
        - nn

test:
    imports:
        - pygridgen

about:
    home: https://github.com/hetland/pygridgen.git
    license:  BSD License
    summary: 'Python interface to gridgen by Pavel Sakov'
