package:
    name: httplib2
    version: "0.9.2"

source:
    fn: httplib2-0.9.2.tar.gz
    url: https://pypi.python.org/packages/source/h/httplib2/httplib2-0.9.2.tar.gz
    md5: bd1b1445b3b2dfa7276b09b1a07b7f0e

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - httplib2

about:
    home: https://github.com/jcgregorio/httplib2
    license: MIT License
    summary: 'A comprehensive HTTP client library.'
