
package:
    name: xarray
    version: 0.7.3.dev0

source:
    git_url: https://github.com/ocefpaf/xarray.git
    git_tag: get_by_attr

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pandas
        - netcdf4
        - scipy
        - bottleneck
        - dask >=0.6
        - h5netcdf
        - cyordereddict
        - pynio  # [not py3k and not win]

test:
    imports:
        - xarray
        - xarray.backends
        - xarray.core
        - xarray.test

about:
    home: https://github.com/pydata/xarray
    license: Apache Software License
    summary: N-D labeled arrays and datasets in Python

extra:
    recipe-maintainers:
        - jhamman
        - ocefpaf
        - shoyer
