package:
    name: quantities
    version: "0.11.1"

source:
    fn: quantities-0.11.1.zip
    url: https://pypi.python.org/packages/source/q/quantities/quantities-0.11.1.zip
    md5: f4c6287bfd2e93322b25a7c1311a0243

build:
    number: 0

requirements:
    build:
      - python
      - numpy
    run:
      - python
      - numpy

test:
    imports:
      - quantities
      - quantities.constants
      - quantities.tests
      - quantities.units

about:
    home: http://pythonhosted.org//quantities/
    license: BSD
    summary: 'Physical quantities with units, based upon Numpy'
