package:
    name: pyugrid
    version: "0.1.6"

source:
    git_url: https://github.com/pyugrid/pyugrid.git
    git_tag: "0.1.6"

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - netcdf4

test:
    imports:
        - pyugrid

about:
    home: https://github.com/pyugrid/pyugrid
    license: BSD
    summary: A Python API to utilize data written using the unstructured grid UGRID conventions.
    home: https://github.com/pyugrid/pyugrid
