package:
    name: oct2py
    version: 3.5.1

source:
    fn: oct2py-3.5.1.tar.gz
    url: https://pypi.python.org/packages/source/o/oct2py/oct2py-3.5.1.tar.gz
    md5: 3ae6ed07712d5817f1bcba8bde1ed6ab

build:
    script: python setup.py install --single-version-externally-managed --record record.txt
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - ipython
        #- octave

#test:
    #imports:
        #- oct2py
        #- oct2py.ipython

about:
    home: http://github.com/blink1073/oct2py
    license: MIT License
    summary: 'Python to GNU Octave bridge --> run m-files from python'

extra:
    recipe-maintainers:
        - ocefpaf
