package:
    name: django-debug-toolbar
    version: "1.4"

source:
    fn: django-debug-toolbar-1.4.tar.gz
    url: https://pypi.python.org/packages/source/d/django-debug-toolbar/django-debug-toolbar-1.4.tar.gz
    md5: 8c9402e11032a76e316fb8e6efe01196

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - django >=1.7
        - sqlparse

test:
    imports:
        - debug_toolbar
        - debug_toolbar.management
        - debug_toolbar.management.commands
        #- debug_toolbar.panels
        #- debug_toolbar.panels.sql
        #- debug_toolbar.panels.templates

about:
    home: https://github.com/django-debug-toolbar/django-debug-toolbar
    license: BSD License
    summary: 'A configurable set of panels that display various debug information about the current request/response.'
