{% set version = "4.3.0a" %}

package:
    name: libspatialite
    version: {{ version }}

source:
    fn: libspatialite-{{ version }}.tar.gz
    url: http://www.gaia-gis.it/gaia-sins/libspatialite-{{ version }}.tar.gz
    md5: 6b380b332c00da6f76f432b10a1a338c
    patches:
        # Skips 3 tests (check_extension, check_sql_stmt, and check_get_normal_zoom_extension_load) that are failing on OS X.
        # Re-visit this once a new release is out.
        - skip_failing_test.patch  # [osx]

build:
    number: 3
    skip: True  # [win]

requirements:
    build:
        - sqlite
        - geos
        - proj.4
        - freexl
        - zlib 1.2*
        - libxml2
        - pkg-config
    run:
        - sqlite
        - geos
        - proj.4
        - freexl
        - zlib 1.2*
        - libxml2
        - libgcc

test:
    commands:
        - test -f ${PREFIX}/lib/libspatialite.a  # [unix]
        - test -f ${PREFIX}/lib/libspatialite.so  # [linux]
        - test -f ${PREFIX}/lib/libspatialite.dylib  # [osx]
        - conda inspect linkages -n _test libspatialite  # [linux]

about:
    home: https://www.gaia-gis.it/fossil/libspatialite/index
    license: LGPL-2.1
    summary: Extend the SQLite core to support fully fledged Spatial SQL capabilities

extra:
    recipe-maintainers:
        - ocefpaf
