package:
    name: algopy
    version: "0.5.3"

source:
    fn: algopy-0.5.3.tar.gz
    url: https://pypi.python.org/packages/source/a/algopy/algopy-0.5.3.tar.gz
    md5: bc2c83b5cb7635fb5b4b309d0312c1bd

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - scipy

test:
    imports:
        - algopy
        - algopy.fft
        - algopy.linalg
        - algopy.nthderiv
        - algopy.special
        - algopy.tests
        - algopy.tracer
        - algopy.tracer.tests
        - algopy.tracer.tests.test_output
        - algopy.utpm
        - algopy.utpm.tests

about:
    home: http://packages.python.org/algopy
    license: BSD
    summary: 'ALGOPY: Taylor Arithmetic Computation and Algorithmic Differentiation'
