package:
    name: pyhdf
    version: "0.9.0"

source:
    fn: pyhdf-0.9.0.tar.gz
    url: http://hdfeos.org/software/pyhdf/pyhdf-0.9.0.tar.gz

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - jpeg
        - numpy x.x
        - zlib
        - hdf4
    run:
        - python
        - numpy x.x
        - jpeg
        - zlib
        - hdf4

test:
    imports:
        - pyhdf

about:
    home:  http://hdfeos.org/software/pyhdf
    license: Public
    summary: 'Python interface to the NCSA HDF4 library'
