package:
    name: betamax
    version: "0.5.0"

source:
    fn: betamax-0.5.0.tar.gz
    url: https://pypi.python.org/packages/source/b/betamax/betamax-0.5.0.tar.gz
    md5: 477727620e225fd19910878d29ad29c1

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - requests >=2.0

test:
    imports:
        - betamax
        - betamax.cassette
        - betamax.matchers
        - betamax.serializers

about:
    home: https://github.com/sigmavirus24/betamax
    license: Apache
    summary: 'A VCR imitation for python-requests'
