package:
    name: expat
    version: 2.1.0

source:
    fn: expat-2.1.0.tar.gz
    url: http://sourceforge.net/projects/expat/files/expat/2.1.0/expat-2.1.0.tar.gz/download

build:
    number: 0

requirements:
    build:
        - msinttypes  # [win]

test:
    commands:
        - xmlwf -h

about:
    home: http://expat.sourceforge.net/
    license: MIT
    summary: Expat XML parser library in C.

extra:
    recipe-maintainers:
        - kwilcox
        - ocefpaf
        - pelson
