package:
    name: matlab_kernel
    version: "0.8.0"

source:
    fn: matlab_kernel-0.8.0-py2.py3-none-any.whl
    url: https://pypi.python.org/packages/py2.py3/m/matlab_kernel/matlab_kernel-0.8.0-py2.py3-none-any.whl
    md5: 9bc3b0823ae5eb7e99153a6036cb5fcc

build:
    number: 0

requirements:
    build:
        - python
        - metakernel >=0.10.5
        - pymatbridge
        - ipython >=3.0
        - ipykernel
    run:
        - python
        - metakernel >=0.10.5
        - pymatbridge
        - ipython >=3.0
        - ipykernel

about:
    home: https://github.com/calysto/matlab_kernel
    license: BSD License
    summary: 'A Matlab kernel for Jupyter/IPython'
