package:
    name: sparqlwrapper
    version: "1.7.6"

source:
    fn: SPARQLWrapper-1.7.6.tar.gz
    url: https://pypi.python.org/packages/source/S/SPARQLWrapper/SPARQLWrapper-1.7.6.tar.gz
    md5: 3d3be71af7720caafa8fc970806e1cb6

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - rdflib >=2.4.2
    run:
        - python
        - rdflib >=2.4.2
        - keepalive

test:
    imports:
        - SPARQLWrapper

about:
    home: http://sparql-wrapper.sourceforge.net/
    license: W3C License
    summary: 'SPARQL Endpoint interface to Python'
