package:
    name: flopy
    version: "3.2.4"

source:
    git_url: https://github.com/modflowpy/flopy.git
    git_tag: 3.2.4

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - numpy
        - matplotlib
    run:
        - python
        - numpy
        - matplotlib

about:
    home: https://github.com/modflowpy/flopy.git
    license: BSD
    summary: 'FloPy is a Python package for developing, running, and post-processing MODFLOW-based models'
