{% set version = "6.1" %}

package:
  name: texinfo
  version: {{ version }}

source:
  fn: texinfo-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/texinfo/texinfo-{{ version }}.tar.gz
  sha256: 02582b6d9b0552f1cb1312be6bd7023e9799603c3b2320fa68a36029e4cbafbb

build:
  number: 0
  skip: True  # [win]

test:
  commands:
    - makeinfo -h
    - conda inspect linkages -p $PREFIX texinfo  # [not win]
    - conda inspect objects -p $PREFIX texinfo  # [osx]

about:
  home: http://www.gnu.org/software/texinfo/
  license: GPL-2.0 and GPL-3.0
  summary: 'The GNU Documentation System.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
