{% set version = "3.1.4" %}

package:
  name: xerces-c
  version: {{ version }}

source:
  fn: xerces-c-{{ version }}.tar.gz
  url: http://apache.uberglobalmirror.com/xerces/c/3/sources/xerces-c-{{ version }}.tar.gz
  sha256: c98eedac4cf8a73b09366ad349cb3ef30640e7a3089d360d40a3dde93f66ecf6

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

about:
  home: http://xerces.apache.org/xerces-c/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Xerces-C++ is a validating XML parser written in a portable subset of C++.'

extra:
  recipe-maintainers:
    - ocefpaf
